
version: '3.8'

services:
  app:
    build: .
    image: emp_aws-app
    ports:
      - "9090:9090"
    networks:
      - my-network
  
   
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword    # required
      MYSQL_DATABASE: emp_aws
      MYSQL_USER: rahul
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
     networks:
      - my-network


networks:
  my-network:
    driver: bridge
   


  

